python: Fix test incompatibility with Python 3.10+
This test failed to build against these versions of Python with
errors like:

  error: lvalue required as unary '&' operand

This was because Py_REFCNT was changed from a macro to a function
as of Python 3.10.

(Internal change: 2338720)